-- DUO SYSTEM secure first-run schema for Supabase. Run once in the SQL Editor.
-- This script creates two private buckets itself; do not create public duplicates.
create extension if not exists pgcrypto;
create type public.app_role as enum ('player','admin','moderator');
create type public.friendship_status as enum ('pending','accepted','rejected','blocked');
create type public.quest_status as enum ('issued','accepted','in_progress','submitted','completed','rejected','expired','cancelled');
create type public.material_visibility as enum ('private','friends','public','admin_only');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade,username text unique not null check(username ~ '^[A-Za-z0-9_]{3,30}$'),display_name text not null check(length(display_name) between 1 and 60),codename text,avatar_url text,bio text check(length(bio)<=500),aspirant_status text default 'aspirant',optional_subject text,favourite_gs_subject text,quote text check(length(quote)<=180),role public.app_role not null default 'player',suspended boolean not null default false,xp integer not null default 0 check(xp>=0),level integer not null default 1 check(level>=1),rank text not null default 'E',leaderboard_opt_in boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.friendships (id uuid primary key default gen_random_uuid(),requester_id uuid not null references public.profiles(id) on delete cascade,addressee_id uuid not null references public.profiles(id) on delete cascade,status public.friendship_status not null default 'pending',created_at timestamptz not null default now(),check(requester_id<>addressee_id));
create unique index friendships_unordered_pair on public.friendships (least(requester_id,addressee_id),greatest(requester_id,addressee_id));
create table public.materials (id uuid primary key default gen_random_uuid(),title text not null check(length(title)<=160),description text check(length(description)<=2000),subject text,category text,file_path text unique not null,uploaded_by uuid not null references public.profiles(id) on delete cascade,visibility public.material_visibility not null default 'private',created_at timestamptz not null default now());
create table public.quests (id uuid primary key default gen_random_uuid(),issuer_id uuid not null references public.profiles(id),target_id uuid not null references public.profiles(id),title text not null check(length(title)<=160),description text check(length(description)<=4000),category text not null default 'Study',difficulty text not null default 'E' check(difficulty in ('E','D','C','B','A','S')),deadline timestamptz,xp_reward int not null check(xp_reward between 1 and 1000),material_id uuid references public.materials(id),is_system boolean not null default false,status public.quest_status not null default 'issued',created_at timestamptz not null default now(),completed_at timestamptz,check(issuer_id<>target_id));
create table public.quest_submissions (id uuid primary key default gen_random_uuid(),quest_id uuid unique not null references public.quests(id) on delete cascade,submitted_by uuid not null references public.profiles(id),evidence_path text,notes text check(length(notes)<=2000),created_at timestamptz not null default now());
create table public.xp_transactions (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id),amount int not null check(amount<>0),reason text not null,quest_id uuid unique references public.quests(id),created_at timestamptz not null default now());
create table public.achievements (id uuid primary key default gen_random_uuid(),code text unique not null,name text not null,description text not null,xp_reward int not null default 0 check(xp_reward>=0),created_at timestamptz not null default now());
create table public.user_achievements (user_id uuid references public.profiles(id) on delete cascade,achievement_id uuid references public.achievements(id) on delete cascade,unlocked_at timestamptz default now(),primary key(user_id,achievement_id));
create table public.notifications (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,title text not null,body text,read_at timestamptz,created_at timestamptz not null default now());
create table public.announcements (id uuid primary key default gen_random_uuid(),title text not null,body text not null,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create index quests_target_status on public.quests(target_id,status);create index quests_issuer_status on public.quests(issuer_id,status);create index notifications_user_created on public.notifications(user_id,created_at desc);create index materials_owner on public.materials(uploaded_by);

create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and not suspended)$$;
create function public.rank_for_xp(v int) returns text language sql immutable as $$select case when v>=10000 then 'SSS' when v>=6000 then 'SS' when v>=3000 then 'S' when v>=1500 then 'A' when v>=700 then 'B' when v>=300 then 'C' when v>=100 then 'D' else 'E' end$$;
create function public.guard_profile() returns trigger language plpgsql as $$begin if (new.role,new.suspended,new.xp,new.level,new.rank) is distinct from (old.role,old.suspended,old.xp,old.level,old.rank) and current_setting('duo.trusted_write',true) is distinct from 'on' then raise exception 'Controlled profile fields are database-managed';end if;new.updated_at=now();return new;end$$;
create trigger profiles_guard before update on public.profiles for each row execute function public.guard_profile();
create function public.apply_xp() returns trigger language plpgsql security definer set search_path=public as $$begin perform set_config('duo.trusted_write','on',true);update public.profiles set xp=xp+new.amount,level=((xp+new.amount)/100)+1,rank=public.rank_for_xp(xp+new.amount) where id=new.user_id;return new;end$$;
create trigger xp_applied after insert on public.xp_transactions for each row execute function public.apply_xp();
create function public.validate_quest_insert() returns trigger language plpgsql security definer set search_path=public as $$begin if new.issuer_id<>auth.uid() and not public.is_admin() then raise exception 'Issuer must be the logged-in player';end if;if new.is_system and not public.is_admin() then raise exception 'System quests require administrator';end if;if not new.is_system and not exists(select 1 from public.friendships where status='accepted' and ((requester_id=new.issuer_id and addressee_id=new.target_id)or(addressee_id=new.issuer_id and requester_id=new.target_id))) then raise exception 'Target must be an accepted friend';end if;return new;end$$;
create trigger quest_insert_guard before insert on public.quests for each row execute function public.validate_quest_insert();
create function public.guard_quest_update() returns trigger language plpgsql security definer set search_path=public as $$begin if current_setting('duo.quest_approval',true)='on' or current_setting('duo.quest_submission',true)='on' then return new;end if; if public.is_admin() then return new;end if;if new.issuer_id<>old.issuer_id or new.target_id<>old.target_id or new.title<>old.title or new.description is distinct from old.description or new.category<>old.category or new.difficulty<>old.difficulty or new.deadline is distinct from old.deadline or new.xp_reward<>old.xp_reward or new.material_id is distinct from old.material_id or new.is_system<>old.is_system or new.completed_at is distinct from old.completed_at then raise exception 'Quest fields cannot be changed';end if;if auth.uid()=old.target_id and ((old.status='issued' and new.status in ('accepted','rejected')) or (old.status='accepted' and new.status='in_progress')) then return new;end if;if auth.uid()=old.issuer_id and old.status='submitted' and new.status='in_progress' then return new;end if;raise exception 'Invalid quest transition';end$$;
create trigger quest_update_guard before update on public.quests for each row execute function public.guard_quest_update();
create function public.approve_quest(p_quest_id uuid) returns void language plpgsql security definer set search_path=public as $$declare q public.quests;begin select * into q from public.quests where id=p_quest_id for update;if not found then raise exception 'Quest not found';end if;if q.issuer_id<>auth.uid() and not public.is_admin() then raise exception 'Only the issuer or administrator may approve';end if;if q.status<>'submitted' then raise exception 'Quest must be submitted before approval';end if;perform set_config('duo.quest_approval','on',true);update public.quests set status='completed',completed_at=now() where id=q.id;insert into public.xp_transactions(user_id,amount,reason,quest_id) values(q.target_id,q.xp_reward,'Quest completion',q.id);insert into public.notifications(user_id,title,body) values(q.target_id,'QUEST COMPLETE','+'||q.xp_reward||' XP awarded');end$$;
create function public.submit_quest(p_quest_id uuid,p_evidence_path text default null,p_notes text default null) returns void language plpgsql security definer set search_path=public as $$declare q public.quests;begin select * into q from public.quests where id=p_quest_id for update;if not found or q.target_id<>auth.uid() or q.status<>'in_progress' then raise exception 'This quest cannot be submitted';end if;if p_evidence_path is not null and p_evidence_path !~ ('^'||auth.uid()::text||'/') then raise exception 'Invalid evidence path';end if;insert into public.quest_submissions(quest_id,submitted_by,evidence_path,notes) values(p_quest_id,auth.uid(),p_evidence_path,p_notes);perform set_config('duo.quest_submission','on',true);update public.quests set status='submitted' where id=p_quest_id;insert into public.notifications(user_id,title,body) values(q.issuer_id,'QUEST SUBMITTED',q.title);end$$;
create function public.unlock_achievement(p_user uuid,p_code text) returns void language plpgsql security definer set search_path=public as $$declare a public.achievements;begin select * into a from public.achievements where code=p_code; if not found then return;end if;insert into public.user_achievements(user_id,achievement_id) values(p_user,a.id) on conflict do nothing; if found then if a.xp_reward>0 then insert into public.xp_transactions(user_id,amount,reason) values(p_user,a.xp_reward,'Achievement: '||a.name);end if;insert into public.notifications(user_id,title,body) values(p_user,'ACHIEVEMENT UNLOCKED',a.name);end if;end$$;
create function public.quest_achievement_check() returns trigger language plpgsql security definer set search_path=public as $$begin if new.status='completed' and old.status<>'completed' then perform public.unlock_achievement(new.target_id,'FIRST_QUEST');if not new.is_system then perform public.unlock_achievement(new.target_id,'STUDY_PARTNER');end if;if new.category='Polity' and (select count(*) from public.quests where target_id=new.target_id and status='completed' and category='Polity')>=10 then perform public.unlock_achievement(new.target_id,'POLITY_SURVIVOR');end if;if new.is_system and (select count(*) from public.quests where target_id=new.target_id and status='completed' and is_system)>=10 then perform public.unlock_achievement(new.target_id,'SYSTEM_FAVOURITE');end if;if extract(hour from new.completed_at at time zone 'UTC') between 0 and 4 then perform public.unlock_achievement(new.target_id,'NIGHT_OWL');end if;end if;return new;end$$;
create trigger quest_achievement_trigger after update on public.quests for each row execute function public.quest_achievement_check();
create function public.friend_achievement_check() returns trigger language plpgsql security definer set search_path=public as $$begin if new.status='accepted' and old.status<>'accepted' then perform public.unlock_achievement(new.addressee_id,'FRIENDSHIP_LINK');end if;return new;end$$;
create trigger friendship_achievement_trigger after update on public.friendships for each row execute function public.friend_achievement_check();
create function public.issue_achievement_check() returns trigger language plpgsql security definer set search_path=public as $$begin if (select count(*) from public.quests where issuer_id=new.issuer_id)>=10 then perform public.unlock_achievement(new.issuer_id,'QUEST_MASTER');end if;return new;end$$;
create trigger issue_achievement_trigger after insert on public.quests for each row execute function public.issue_achievement_check();
create function public.level_achievement_check() returns trigger language plpgsql security definer set search_path=public as $$begin if new.level>=10 and old.level<10 then perform public.unlock_achievement(new.id,'LEVEL_10');end if;return new;end$$;
create trigger level_achievement_trigger after update on public.profiles for each row execute function public.level_achievement_check();

alter table public.profiles enable row level security;alter table public.friendships enable row level security;alter table public.quests enable row level security;alter table public.quest_submissions enable row level security;alter table public.materials enable row level security;alter table public.xp_transactions enable row level security;alter table public.achievements enable row level security;alter table public.user_achievements enable row level security;alter table public.notifications enable row level security;alter table public.announcements enable row level security;
create policy "profile read" on public.profiles for select to authenticated using(not suspended or id=auth.uid() or public.is_admin());create policy "profile create self" on public.profiles for insert to authenticated with check(id=auth.uid() and role='player' and not suspended and xp=0 and level=1 and rank='E');create policy "profile update self" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "friend read participant" on public.friendships for select to authenticated using(auth.uid() in(requester_id,addressee_id) or public.is_admin());create policy "friend create self" on public.friendships for insert to authenticated with check(requester_id=auth.uid() and requester_id<>addressee_id);create policy "friend response" on public.friendships for update to authenticated using(addressee_id=auth.uid() or public.is_admin()) with check(addressee_id=auth.uid() or public.is_admin());create policy "friend remove participant" on public.friendships for delete to authenticated using(auth.uid() in(requester_id,addressee_id) or public.is_admin());
create policy "quest read participant" on public.quests for select to authenticated using(auth.uid() in(issuer_id,target_id) or public.is_admin());create policy "quest issue" on public.quests for insert to authenticated with check(issuer_id=auth.uid() or public.is_admin());create policy "quest transition participant" on public.quests for update to authenticated using(auth.uid() in(issuer_id,target_id) or public.is_admin()) with check(auth.uid() in(issuer_id,target_id) or public.is_admin());
create policy "submission read participant" on public.quest_submissions for select to authenticated using(exists(select 1 from public.quests q where q.id=quest_id and (auth.uid() in(q.issuer_id,q.target_id) or public.is_admin())));
create policy "material read authorized" on public.materials for select to authenticated using(uploaded_by=auth.uid() or visibility='public' or public.is_admin() or (visibility='friends' and exists(select 1 from public.friendships f where f.status='accepted' and ((f.requester_id=materials.uploaded_by and f.addressee_id=auth.uid())or(f.addressee_id=materials.uploaded_by and f.requester_id=auth.uid())))));create policy "material create self" on public.materials for insert to authenticated with check(uploaded_by=auth.uid() or public.is_admin());create policy "material update owner" on public.materials for update to authenticated using(uploaded_by=auth.uid() or public.is_admin()) with check(uploaded_by=auth.uid() or public.is_admin());create policy "material delete owner" on public.materials for delete to authenticated using(uploaded_by=auth.uid() or public.is_admin());
create policy "xp read own" on public.xp_transactions for select to authenticated using(user_id=auth.uid() or public.is_admin());create policy "achievement catalog" on public.achievements for select to authenticated using(true);create policy "achievement admin" on public.achievements for all to authenticated using(public.is_admin()) with check(public.is_admin());create policy "user achievements own" on public.user_achievements for select to authenticated using(user_id=auth.uid() or public.is_admin());create policy "notifications own" on public.notifications for select to authenticated using(user_id=auth.uid() or public.is_admin());create policy "announcements read" on public.announcements for select to authenticated using(true);create policy "announcements admin" on public.announcements for all to authenticated using(public.is_admin()) with check(public.is_admin());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('avatars','avatars',false,2097152,array['image/jpeg','image/png','image/webp']),('materials','materials',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp','text/plain','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']),('evidence','evidence',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp','text/plain']);
create policy "avatar insert owner folder" on storage.objects for insert to authenticated with check(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.jwt()->>'sub'));
create policy "avatar read owner" on storage.objects for select to authenticated using(bucket_id='avatars' and owner_id=(select auth.uid()::text));
create policy "avatar update owner" on storage.objects for update to authenticated using(bucket_id='avatars' and owner_id=(select auth.uid()::text)) with check(bucket_id='avatars' and owner_id=(select auth.uid()::text));
create policy "material insert owner folder" on storage.objects for insert to authenticated with check(bucket_id='materials' and (storage.foldername(name))[1]=(select auth.jwt()->>'sub'));
create policy "material read authorized" on storage.objects for select to authenticated using(bucket_id='materials' and exists(select 1 from public.materials m where m.file_path=name));
create policy "material update owner" on storage.objects for update to authenticated using(bucket_id='materials' and owner_id=(select auth.uid()::text)) with check(bucket_id='materials' and owner_id=(select auth.uid()::text));
create policy "material delete owner" on storage.objects for delete to authenticated using(bucket_id='materials' and owner_id=(select auth.uid()::text));
create policy "evidence insert owner folder" on storage.objects for insert to authenticated with check(bucket_id='evidence' and (storage.foldername(name))[1]=(select auth.jwt()->>'sub'));
create policy "evidence read participant" on storage.objects for select to authenticated using(bucket_id='evidence' and exists(select 1 from public.quest_submissions s join public.quests q on q.id=s.quest_id where s.evidence_path=name and (auth.uid() in(q.issuer_id,q.target_id) or public.is_admin())));

revoke all on function public.approve_quest(uuid) from public;revoke all on function public.submit_quest(uuid,text,text) from public;grant execute on function public.approve_quest(uuid) to authenticated;grant execute on function public.submit_quest(uuid,text,text) to authenticated;
-- After creating the first player, manually promote exactly one account in SQL Editor:
-- begin; select set_config('duo.trusted_write','on',true); update public.profiles set role='admin' where username='your_admin_username'; commit;
